---
- name: Configure IBM MQ objects
  hosts: mqservers
  become: true
  become_method: sudo
  become_user: root


  tasks:

    - name: Validate queue configuration
      ansible.builtin.include_tasks: 
        file: ../validation/queue_validation.yml


    - name: configure queue
      ansible.builtin.include_tasks: 
        file: ../tasks/configure_queues.yml

    - name: validate channel configuration
      ansible.builtin.include_tasks:
        file: ../validation/validate_channels.yml
    
    - name: configure channel
      ansible.builtin.include_tasks: 
        file: ../tasks/configure_channels.yml

    - name: validate listener configurations
      ansible.builtin.include_tasks:
        file: ../validation/validate_listeners.yml

    - name: configure listener
      ansible.builtin.include_tasks:
        file: ../tasks/configure_listeners.yml

    - name: Validate topic configurations
      ansible.builtin.include_tasks: 
        file: ../validation/validate_topics.yml

    - name: configure topics 
      ansible.builtin.include_tasks:
        file: ../tasks/configure_topics.yml

    - name: validate Subscription configurations
      ansible.builtin.include_tasks:
        file: ../validation/validate_subscriptions.yml

    - name: configure mq_subscriptions 
      ansible.builtin.include_tasks:
        file: ../tasks/configure_subscriptions.yml

    - name: configure auth records 
      ansible.builtin.include_tasks:
        file: ../tasks/configure_authrecords.yml

    - name: configure CHLAUTH records
      ansible.builtin.include_tasks:
        file: ../tasks/configure_chlauth.yml
    


    # - name: check queue status
    #   ansible.builtin.shell: |
    #     echo "DIS QUEUE('{{ queue.name }}') MAXDEPTH" |
    #     sudo -u mqm {{ mq_dir }}/runmqsc {{ queue.host_qmgr }}
    #   loop: "{{ mq_queues }}"
    #   loop_control:
    #     loop_var: queue
    #   register: queue_check
    #   changed_when: false
    #   failed_when: false


    # - name: Check channel status
    #   ansible.builtin.shell: |
    #     echo "DIS CHANNEL('{{ channel.name }}')" |
    #     sudo -u mqm {{ mq_dir }}/runmqsc {{ channel.host_qmgr }}
    #   loop: "{{ mq_channel }}"
    #   loop_control:
    #     loop_var: channel
    #   register: channel_check
    #   failed_when: false
    #   changed_when: false

    # - name: Check listener status
    #   ansible.builtin.shell: | 
    #     echo "DIS LISTENER('{{ listener.name }}')" | 
    #     sudo -u mqm {{ mq_dir }}/runmqsc {{ listener.host_qmgr }}
    #   loop: "{{ mq_listeners }}"
    #   loop_control: 
    #     loop_var: listener
    #   register: listener_check
    #   failed_when: false
    #   changed_when: false


    # - name: Create Queues
    #   ansible.builtin.shell: |
    #     {% if queue.type == 'xmitq' %}
    #     echo "DEFINE QL('{{ queue.name }}') MAXDEPTH({{ queue.max_depth }}) USAGE(XMITQ)"|
    #     sudo -u mqm {{ mq_dir }}/runmqsc {{ queue.host_qmgr }}

    #     {% elif queue.type == 'remote' %}
    #     echo "DEFINE QREMOTE('{{ queue.name }}') RNAME('{{ queue.rname }}') RQMNAME('{{ queue.remote_qmgr }}') XMITQ('{{ queue.xmit_queue }}') " |
    #     sudo -u mqm {{ mq_dir }}/runmqsc {{ queue.host_qmgr }}

    #     {% elif queue.type == 'alias' %}
    #     echo "DEFINE QALIAS('{{ queue.name }}') TARGQ('{{ queue.target_queue }}')" |
    #     sudo -u mqm {{ mq_dir }}/runmqsc {{ queue.host_qmgr}}

    #     {% else %}
    #     echo "DEFINE QL('{{ queue.name }}') MAXDEPTH({{ queue.max_depth }})" |
    #     sudo -u mqm {{ mq_dir }}/runmqsc {{ queue.host_qmgr }}
    #     {% endif %}

    #   loop: "{{ mq_queues }}"
    #   loop_control:
    #     loop_var: queue
    #     index_var: queue_index
    #     label: "{{ queue.name }} on {{ queue.host_qmgr }}"
    #   when: queue_check.results[queue_index].rc != 0

    # - name: Create MQ Channel
    #   ansible.builtin.shell: |
    #     {%if channel.type == 'SDR' %}
    #     echo "DEFINE CHANNEL('{{ channel.name }}') CHLTYPE({{ channel.type }}) CONNAME('{{ channel.target_host }}({{ channel.target_port }})') XMITQ('{{ channel.xmit_queue }}')" |
    #     sudo -u mqm {{ mq_dir }}/runmqsc {{ channel.host_qmgr }}
    #     {% else %}
    #     echo "DEFINE CHANNEL('{{ channel.name }}') CHLTYPE({{ channel.type }})" |
    #     sudo -u mqm {{ mq_dir }}/runmqsc {{ channel.host_qmgr }}
    #     {% endif %}
    #   loop: "{{ mq_channel }}"
    #   loop_control:
    #     loop_var: channel
    #     index_var: channel_index
    #     label: "{{ channel.name }} on {{ channel.host_qmgr }}"
    #   when: channel_check.results[channel_index].rc !=0

    # - name: create MQ listeners 
    #   ansible.builtin.shell: | 
    #     echo "DEFINE LISTENER('{{ listener.name }}') TRPTYPE(TCP) PORT({{ listener.port}}) CONTROL({{ listener.control }})"|
    #     sudo -u mqm {{ mq_dir }}/runmqsc {{ listener.host_qmgr }}
    #   loop: "{{ mq_listeners }}"
    #   loop_control: 
    #     loop_var: listener
    #     index_var: listener_index
    #     label: "{{ listener.name }} on {{ listener.host_qmgr }}"
    #   when: listener_check.results[listener_index].rc !=0
